# admin.html → admin_page.js (a JS module exporting the page as a string, bundled into the Worker)
import json, pathlib
here = pathlib.Path(__file__).parent
html = (here / 'admin.html').read_text(encoding='utf-8')
(here / 'admin_page.js').write_text('// generated by make_admin.py from admin.html — edit admin.html instead\nexport default ' + json.dumps(html, ensure_ascii=False) + ';\n', encoding='utf-8')
print('admin_page.js', len(html))
