# stats.html → stats_page.js (bundled into the Worker)
import json, pathlib
h = pathlib.Path(__file__).parent
(h / 'stats_page.js').write_text('// generated by make_stats.py from stats.html — edit stats.html instead\nexport default ' + json.dumps((h / 'stats.html').read_text(encoding='utf-8'), ensure_ascii=False) + ';\n', encoding='utf-8')
print('ok')
